jwt:
    expires-time: 7d
    buffer-time: 1d
local:
    path: uploads/file
    store-path: uploads/file
system:
    addr: 8004
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: xzs
    username: root
    password: ""
    path: 127.0.0.1
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false